FROM python:3.9-slim

WORKDIR /app

# Install uv
RUN pip install uv

COPY ../server/requirements.txt .
RUN uv pip install -r requirements.txt

COPY ../server/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"] 